version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     networks:
       - wpnet

   wp:
     depends_on:
       - db
     image: wordpress
     volumes:
       - ./htdocs:/var/www/html
       - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
       WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
     networks:
       - wpnet

   pma:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     ports:
       - "1234:80"
     restart: always
     environment:
       PMA_HOST: db
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     networks:
       - wpnet

networks:
  wpnet:     
volumes:
  htdocs:
  db_data:
